#!/bin/bash
#$ -cwd
#$ -o PATHWAY_TO_LOGFILE
#$ -M EMAIL_ADDRESS


source PATHWAY_TO_PYTHON_ENVIRONMENT/bin/activate


LOG_FILE="PATHWAY_TO_LOGFILE"
IN_TWEET_FILE="PATHWAY_TO_INPUT_DATA"
OUT_RESULTS_FILE="PATHWAY_TO_OUTPUT_DATA"

python3 PATHWAY_TO_tw_extract_org_request_urls.py  $LOG_FILE $IN_TWEET_FILE $OUT_RESULTS_FILE
